"use client";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Bell, BookOpen, CalendarDays, CheckCircle2, ChevronRight, Clock3, ExternalLink, LayoutDashboard, Moon, RefreshCw, Settings, Sun, Target, TrendingUp } from "lucide-react";

type Event = { id:string; date:string; country:string; name:string; impact:"High"|"Average"; actual?:string|number; forecast?:string|number; previous?:string|number; source:string; url?:string };
type View = "overview"|"calendar"|"maps"|"journal";
const maps: Record<string,string[]> = { "United States":["XAUUSD","EURUSD","USDJPY","GBPUSD"],"Euro Area":["EURUSD","EURGBP"],"United Kingdom":["GBPUSD","EURGBP"],Japan:["USDJPY","XAUUSD"],Canada:["USDCAD","WTI"],Australia:["AUDUSD","Copper"],"New Zealand":["NZDUSD","AUDNZD"],Switzerland:["USDCHF","XAUUSD"],China:["AUDUSD","Copper","Soybeans"] };
function eventMap(e:Event){ return maps[e.country] || (/gas/i.test(e.name)?["Natural Gas"]:/wasde|crop|grain/i.test(e.name)?["Corn","Soybeans"]:/oil|crude/i.test(e.name)?["WTI","USDCAD"]:["XAUUSD","EURUSD"]); }
function format(d:string){ return new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(d)); }
function timeLeft(d?:string){if(!d)return "—";const s=Math.max(0,Math.floor((+new Date(d)-Date.now())/1000));return `${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor(s/60)%60).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;}
function playbook(e?:Event){const name=e?.name||"the release"; if(/cpi|pce|inflation/i.test(name))return {driver:"Inflation → real yields → Fed path",base:"Hotter-than-consensus inflation usually lifts yields and USD, pressuring XAUUSD. Cooler inflation can reduce expected policy restraint and support gold.",watch:"Compare the surprise with market pricing first. Watch the 1-minute initial move, then wait for the 5-minute candle close and yield/DXY confirmation before treating a direction as established."};if(/employment|non farm|jobless|jolts|wage/i.test(name))return {driver:"Labour tightness → wage pressure → policy path",base:"A stronger labour surprise can support USD; weaker jobs or softer wages can support XAUUSD. Wage growth and revisions can outweigh the headline jobs number.",watch:"Watch US 2Y yield, DXY and the 5-minute post-release close. NFP spreads/slippage are often extreme at the first tick."};if(/rate|monetary|fomc|central bank/i.test(name))return {driver:"Rate decision + guidance + positioning",base:"The decision versus expectations matters less than the statement, projections and press conference. An expected decision can still move sharply if guidance changes.",watch:"Use 5-minute candles through the decision; do not treat the first wick as confirmation. Read the statement before placing directional risk."};if(/storage|crude|oil|gas/i.test(name))return {driver:"Inventory surprise versus seasonal demand",base:"A larger-than-expected crude build can pressure WTI; a draw can support it. Natural-gas storage is highly weather and season dependent.",watch:"Compare the inventory surprise with API estimates, refinery utilization and weather. Wait for a 5-minute close in the contract."};return {driver:"Surprise versus consensus + current positioning",base:"The market usually reacts to the surprise, revisions and what the data changes for policy or demand—not the headline in isolation.",watch:"Use the 1-minute move for information, then the 5-minute close plus related market confirmation for execution context."};}

export default function Dashboard(){
 const [ready,setReady]=useState(false),[view,setView]=useState<View>("overview"),[events,setEvents]=useState<Event[]>([]),[range,setRange]=useState("week"),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[dark,setDark]=useState(true),[selected,setSelected]=useState<Event>(),[now,setNow]=useState(Date.now()),[checks,setChecks]=useState<string[]>([]),[settings,setSettings]=useState(false);
 const load=async()=>{setLoading(true);try{const d=await fetch(`/api/calendar?window=${range}`).then(r=>r.json());setEvents(d.events||[]);setMessage(d.message||"");}catch{setMessage("Could not reach the live calendar.");}finally{setLoading(false)}};
 useEffect(()=>{setReady(true);load()},[range]);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 const upcoming=useMemo(()=>events.filter(e=>+new Date(e.date)>now).sort((a,b)=>+new Date(a.date)-+new Date(b.date)),[events,now]); const next=upcoming[0]; const detail=playbook(selected||next);
 if(!ready)return <main className="boot"/>;
 const nav=(id:View,label:string,Icon:typeof LayoutDashboard)=><button onClick={()=>setView(id)} className={view===id?"nav active":"nav"}><Icon size={17}/>{label}</button>;
 const eventList=(list:Event[])=>list.length?list.map(e=><button className={selected?.id===e.id?"event selected":"event"} onClick={()=>{setSelected(e);setView("overview")}} key={e.id}><span className={checks.includes(e.id)?"check done":"check"} onClick={x=>{x.stopPropagation();setChecks(v=>v.includes(e.id)?v.filter(i=>i!==e.id):[...v,e.id])}}>{checks.includes(e.id)&&<CheckCircle2 size={13}/>}</span><span className="when">{format(e.date)}</span><span className="event-main"><b>{e.name}</b><small>{e.country} · {eventMap(e).join(" · ")}</small></span><span className={e.impact==="High"?"impact high":"impact"}>{e.impact}</span><ChevronRight size={16}/></button>):<div className="empty"><Bell size={20}/><b>No high-impact events loaded</b><span>{message||"No major event in this selected period."}</span></div>;
 return <main className={dark?"app dark":"app"}><aside className="side"><div className="brand"><i>◇</i><span>Market Pulse<small>NEWS TRADING HQ</small></span></div><nav>{nav("overview","Overview",LayoutDashboard)}{nav("calendar","Economic calendar",CalendarDays)}{nav("maps","Market maps",TrendingUp)}{nav("journal","Trade journal",BookOpen)}</nav><div className="side-bottom"><button className="nav" onClick={()=>setSettings(true)}><Settings size={17}/>Data settings</button><p>High-impact events only<br/>Times use your device timezone.</p></div></aside><section className="content"><header><div><span className="crumb">WORKSPACE / {view.toUpperCase()}</span><h1>{view==="overview"?"Trading home":view==="calendar"?"Economic calendar":view==="maps"?"Market maps":"Trade journal"}</h1></div><div className="head-actions"><button className="ghost" onClick={()=>setSettings(true)}><Settings size={15}/>Connect data</button><button className="theme" onClick={()=>setDark(x=>!x)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button></div></header>
 {view==="overview"&&<><section className="hero"><div><span className="live-dot">LIVE CALENDAR</span><h2>{next?.name||"Calendar connection required"}</h2><p>{next?`${format(next.date)} · ${next.country} · ${eventMap(next).join(" / ")}`:message||"Connect TradingEconomics to show verified event dates."}</p><div className="tags">{next&&eventMap(next).map(x=><span key={x}>{x}</span>)}</div></div><div className="timer"><Clock3 size={16}/><strong>{timeLeft(next?.date)}</strong><small>UNTIL RELEASE</small></div></section><section className="overview-grid"><div className="panel"><div className="panel-head"><div><h3>Upcoming catalysts</h3><p>Click an event for its playbook.</p></div><button className="small" onClick={()=>setView("calendar")}>Full calendar</button></div>{loading?<div className="empty">Loading verified calendar…</div>:eventList(upcoming.slice(0,7))}</div><div className="panel intelligence"><span className="section-label">PRE-EVENT INTELLIGENCE</span><h3>{selected?.name||next?.name||"Select a live event"}</h3><div className="driver"><b>Core driver</b><span>{detail.driver}</span></div><p>{detail.base}</p><div className="watch"><Clock3 size={15}/><span>{detail.watch}</span></div>{(selected||next)&&<div className="links"><a target="_blank" href={(selected||next)?.url||"https://www.investing.com/economic-calendar/"}>Release calendar <ExternalLink size={13}/></a><a target="_blank" href={`https://www.tradingview.com/chart/?symbol=${eventMap(selected||next!)[0]}`}>Open chart <ExternalLink size={13}/></a></div>}</div></section></>}
 {view==="calendar"&&<section className="panel calendar"><div className="panel-head"><div><h3>Verified economic calendar</h3><p>Actual, forecast and previous values come directly from the provider.</p></div><button className="ghost" onClick={load}><RefreshCw size={15}/>Refresh</button></div><div className="tabs">{[["week","Daily / weekly"],["month","Monthly"],["quarter","Quarterly"],["sixMonths","6 months"]].map(([k,l])=><button onClick={()=>setRange(k)} className={range===k?"tab selected":"tab"} key={k}>{l}</button>)}</div>{loading?<div className="empty">Loading verified calendar…</div>:<div className="table">{upcoming.map(e=><button onClick={()=>{setSelected(e);setView("overview")}} className="table-row" key={e.id}><span>{format(e.date)}</span><b>{e.name}<small>{e.country} · {eventMap(e).join(" · ")}</small></b><span><small>Forecast</small>{e.forecast??"—"}</span><span><small>Previous</small>{e.previous??"—"}</span><i className={e.impact==="High"?"impact high":"impact"}>{e.impact}</i></button>)}</div>}</section>}
 {view==="maps"&&<section className="maps"><p className="intro">Your focused instruments and the reports that can materially change their macro narrative.</p>{[["USD macro",["XAUUSD","EURUSD","GBPUSD","USDJPY"]],["Commodity demand",["Copper","Natural Gas","Corn","Soybeans"]],["Central-bank divergence",["EURGBP","AUDUSD","NZDUSD","USDCAD","USDCHF"]]].map(([title,markets])=><section className="panel map" key={title as string}><h3>{title as string}</h3><div>{(markets as string[]).map(m=><button key={m} onClick={()=>window.open(`https://www.tradingview.com/chart/?symbol=${m}`,"_blank")}><BarChart3 size={17}/><b>{m}</b><span>{m==="XAUUSD"?"CPI · PCE · FOMC · real yields":m==="Natural Gas"?"EIA storage · NOAA weather":m==="Corn"||m==="Soybeans"?"WASDE · crop progress · grain stocks":"Central banks · inflation · jobs"}</span><ExternalLink size={14}/></button>)}</div></section>)}</section>}
 {view==="journal"&&<section className="panel journal"><h3>Trade journal</h3><p>Sign in and connect Supabase to save entries securely across devices. Until then, use the event checkmarks as a local pre-trade checklist.</p><button className="primary" onClick={()=>setSettings(true)}>Set up account and database</button></section>}
 </section>{settings&&<div className="modal-back" onClick={()=>setSettings(false)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSettings(false)}>×</button><span className="section-label">SECURE DATA SETUP</span><h2>Connect production data</h2><p>API secrets cannot safely be accepted or written to a `.env` file from a browser. They must stay in Vercel environment variables, where users cannot extract them.</p><ol><li>Create a TradingEconomics API key.</li><li>In your project’s `.env.local`, add <code>TRADING_ECONOMICS_KEY=your_key</code>.</li><li>For Vercel: Project → Settings → Environment Variables → add the same key, then redeploy.</li><li>Add Supabase URL and anon key from `.env.example` to enable individual accounts.</li></ol><a className="primary link-button" target="_blank" href="https://tradingeconomics.com/api/">Open TradingEconomics API <ExternalLink size={14}/></a></section></div>}</main>;
}
